# kubectl create ns stonebird
# kubectl apply -f prometheus.yaml
# promethues pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promethues-data
  namespace: stonebird
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: rook-cephfs
---
apiVersion: v1
kind: ConfigMap
metadata:
  name:  promethues-cm
  namespace: stonebird
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'metrics'
        metrics_path: /metrics
        scrape_interval: 5s
        static_configs:
          - targets: ['metrics:6789']   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promethues
  namespace: stonebird
  labels:
    app: promethues
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promethues
  template:
    metadata:
      labels:
        app: promethues
    spec:
      containers:
      - name: promethues-container
        image: prometheus
        imagePullPolicy: IfNotPresent
        args:
        - "--config.file=/etc/prometheus/prometheus.yml"
        - "--storage.tsdb.path=/etc/prometheus/data"  # 指定tsdb数据路径
        - "--storage.tsdb.retention.time=180d" # 数据保存时间
        - "--web.enable-admin-api"  # 控制对admin HTTP API的访问，其中包括删除时间序列等功能
        - "--web.enable-lifecycle"  # 支持热更新，直接执行localhost:9090/-/reload立即生效
        ports:
        - containerPort: 9090
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "2"
            memory: 4Gi
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /-/healthy
            port: 9090
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: "/etc/prometheus/data"
          name: promethues-storage
        - mountPath: /etc/prometheus/prometheus.yml
          name: prometheus-config
          readOnly: true
          subPath: prometheus.yml  
      volumes:
      - name: promethues-storage
        persistentVolumeClaim:
          claimName: promethues-data
      - name: prometheus-config
        configMap: 
          defaultMode: 420
          name: promethues-cm

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: stonebird
  labels:
    app: promethues
spec:
  selector:
    app: promethues
  type: NodePort
  ports:
    - name: promethues
      port: 9090
      nodePort: 32090
      targetPort: 9090
      protocol: TCP
