apiVersion: rocketmq.apache.org/v1alpha1
kind: NameService
metadata:
  name: iva-rocketmq-nameserver
  namespace: {{ .Values.namespace }}
spec:
  size: 1
  nameServiceImage: {{ .Values.nameserver.image }}
  imagePullPolicy: {{ .Values.imagePullPolicy }} 
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  resources:
    requests:
      memory: "2Gi"
      cpu: "1000m"
    limits:
      memory: "2Gi"
      cpu: "2000m"
  # storageMode can be EmptyDir, HostPath, StorageClass
  storageMode: StorageClass
  # hostPath is the local path to store data
  hostPath: /data/rocketmq/nameserver
  # volumeClaimTemplates defines the storageClass
  volumeClaimTemplates:
    - metadata:
        name: namesrv-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.storageClass }} 
        resources:
          requests:
            storage: {{ .Values.nameserver.storageSize }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: broker-config
  namespace: {{ .Values.namespace }}
data:
  # BROKER_MEM sets the broker JVM, if set to "" then Xms = Xmx = max(min(1/2 ram, 1024MB), min(1/4 ram, 8GB))
  BROKER_MEM: " -Xms2g -Xmx2g -Xmn1g "
  broker-common.conf: |
    # brokerClusterName, brokerName, brokerId are automatically generated by the operator and do not set it manually!!!
    deleteWhen=04
    fileReservedTime=48
    flushDiskType=ASYNC_FLUSH
    # set brokerRole to ASYNC_MASTER or SYNC_MASTER. DO NOT set to SLAVE because the replica instance will automatically be set!!!
    brokerRole=ASYNC_MASTER

---
apiVersion: rocketmq.apache.org/v1alpha1
kind: Broker
metadata:
  # name of broker cluster
  name: iva-rocketmq-broker
  namespace: {{ .Values.namespace }}
spec:
  hostNetwork: true
  # size is the number of the broker cluster, each broker cluster contains a master broker and [replicaPerGroup] replica brokers.
  size: {{ .Values.broker.replicas }}
  # replicaPerGroup is the number of each broker cluster
  replicaPerGroup: 1
  brokerImage: {{ .Values.broker.image }}
  imagePullPolicy: {{ .Values.imagePullPolicy }}
  resources:
    requests:
      memory: "4Gi"
      cpu: "2000m"
    limits:
      memory: "4Gi"
      cpu: "4000m"
  allowRestart: true
  # storageMode can be EmptyDir, HostPath, StorageClass
  storageMode: StorageClass
  # hostPath is the local path to store data
  hostPath: /data/rocketmq/broker
  # scalePodName is [Broker name]-[broker group number]-master-0
  scalePodName: iva-rocketmq-broker-0-master-0
  env:
    - name: BROKER_MEM
      valueFrom:
        configMapKeyRef:
          name: broker-config
          key: BROKER_MEM
  # volumes defines the broker.conf
  volumes:
    - name: broker-config
      configMap:
        name: broker-config
        items:
          - key: broker-common.conf
            path: broker-common.conf
  # volumeClaimTemplates defines the storageClass
  volumeClaimTemplates:
    - metadata:
        name: broker-storage
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.storageClass }}
        resources:
          requests:
            storage: {{ .Values.broker.storageSize }}

---
apiVersion: rocketmq.apache.org/v1alpha1
kind: Console
metadata:
  name: iva-rocketmq-console
  namespace: {{ .Values.namespace }}
spec:
  # nameServers is the [ip:port] list of name service
  nameServers: "iva-rocketmq-nameserver:9876"
  # consoleDeployment define the console deployment
  consoleDeployment:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: iva-rocketmq-console
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: iva-rocketmq-console
      template:
        metadata:
          labels:
            app: iva-rocketmq-console
        spec:
          containers:
            - name: console
              image: {{ .Values.console.image }}
              ports:
                - containerPort: 8080