apiVersion: v1
kind: Service
metadata:
  name: iva-rocketmq-console
  labels:
    app: iva-rocketmq-console
spec:
  type: NodePort
  selector:
    app: iva-rocketmq-console
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 32080
---
apiVersion: v1
kind: Service
metadata:
  name: iva-rocketmq-nameserver
spec:
  type: NodePort
  selector:
    name_service_cr: iva-rocketmq-nameserver
  ports:
    - port: 9876
      targetPort: 9876
      nodePort: 32076